services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - '127.0.0.1:3000:3000'
    volumes:
      - listening-data:/app/data
    env_file:
      - .env

volumes:
  listening-data:
