export const site = {
	title: 'Michael Schultz',
	author: 'Michael Schultz',
	headerTitle: 'Michael Schultz',
	description: 'Michael Schultz | software and design',
	language: 'en-us',
	defaultTheme: 'dark' as const,
	siteUrl: 'https://michaelschultz.com',
	siteRepo: 'https://github.com/michaelwschultz/michaelschultz.com',
	siteLogo: '/static/images/logo.png',
	socialBanner: '/static/images/michael-schultz-social.jpg',
	email: 'hi@michaelschultz.com',
	github: 'https://github.com/michaelwschultz',
	bluesky: 'https://bsky.app/profile/michaelschultz.com',
	locale: 'en-US',
} as const;
